import type { Sticker } from "../entities.js";
import { StickerCategory, StickerEra, StickerRarity } from "../enums.js";

export const INITIAL_STICKER_SEED_MIN_EXPECTED = 50;
const SEED_TIMESTAMP = new Date("2026-01-01T00:00:00.000Z");
const LIBERTADORES_2014_TAG = "libertadores-2014";
const LIBERTADORES_2014_IMAGE_URLS = [
  "/stickers/Libertadores_2014/libertadores_1.png",
  "/stickers/Libertadores_2014/libertadores_2.png",
  "/stickers/Libertadores_2014/libertadores_3.png",
  "/stickers/Libertadores_2014/Libertadores_4.jpg",
  "/stickers/Libertadores_2014/Libertadores_6.jpg",
  "/stickers/Libertadores_2014/libertadores_6.png",
  "/stickers/Libertadores_2014/libertadores_7.png",
  "/stickers/Libertadores_2014/libertadores_8.jpg",
  "/stickers/Libertadores_2014/libertadores_9.jpg",
  "/stickers/Libertadores_2014/libertadores_10.jpg",
  "/stickers/Libertadores_2014/libertadores_11.jpg",
  "/stickers/Libertadores_2014/libertadores_12.jpg",
  "/stickers/Libertadores_2014/libertadores_13.jpg",
  "/stickers/Libertadores_2014/libertadores_14.png",
  "/stickers/Libertadores_2014/libertadores_15.png",
  "/stickers/Libertadores_2014/libertadores_16.png",
  "/stickers/Libertadores_2014/libertadores_17.png",
  "/stickers/Libertadores_2014/libertadores_18.png",
  "/stickers/Libertadores_2014/libertadores_19.jpg",
  "/stickers/Libertadores_2014/libertadores_20.png",
  "/stickers/Libertadores_2014/libertadores_21.jpg",
  "/stickers/Libertadores_2014/libertadores_22.jpg",
  "/stickers/Libertadores_2014/libertadores_23.jpg",
  "/stickers/Libertadores_2014/libertadores_24.jpg",
  "/stickers/Libertadores_2014/libertadores_25.png",
  "/stickers/Libertadores_2014/libertadores_26.png",
  "/stickers/Libertadores_2014/libertadores_27.png",
  "/stickers/Libertadores_2014/libertadores_28.png",
  "/stickers/Libertadores_2014/libertadores_29.jpg",
  "/stickers/Libertadores_2014/libertadores_30.png",
  "/stickers/Libertadores_2014/libertadores_31.png",
  "/stickers/Libertadores_2014/libertadores_32.png",
  "/stickers/Libertadores_2014/libertadores_33.png",
] as const;

export const initialStickerSeed: readonly Sticker[] = [
  libertadoresSticker(
    1,
    "sl-001",
    "Viejo Gasometro",
    StickerCategory.STADIUM,
    StickerRarity.LEGENDARY,
    ["boedo", "estadio", "historia"],
  ),
  libertadoresSticker(
    2,
    "sl-002",
    "Capitan de los Matadores",
    StickerCategory.PLAYER,
    StickerRarity.EPIC,
    ["jugador", "matadores"],
  ),
  libertadoresSticker(
    3,
    "sl-003",
    "Goleador azulgrana 40s",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "goleador"],
  ),
  libertadoresSticker(
    4,
    "sl-004",
    "Arquero historico",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "arquero"],
  ),
  libertadoresSticker(
    5,
    "sl-005",
    "Director tecnico clasico",
    StickerCategory.COACH,
    StickerRarity.COMMON,
    ["tecnico", "historia"],
  ),
  libertadoresSticker(
    6,
    "sl-006",
    "Campeonato invicto",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.RARE,
    ["campeonato", "invicto"],
  ),
  libertadoresSticker(
    7,
    "sl-007",
    "Tarde de Boedo",
    StickerCategory.HISTORIC_MOMENT,
    StickerRarity.UNCOMMON,
    ["momento", "boedo"],
  ),
  libertadoresSticker(
    8,
    "sl-008",
    "Camiseta bastones clasica",
    StickerCategory.JERSEY,
    StickerRarity.COMMON,
    ["camiseta", "clasica"],
  ),
  libertadoresSticker(
    9,
    "sl-009",
    "Hinchas en avenida La Plata",
    StickerCategory.FANS,
    StickerRarity.COMMON,
    ["hinchada", "boedo"],
  ),
  libertadoresSticker(
    10,
    "sl-010",
    "Clasico de barrio historico",
    StickerCategory.CLASSIC_MATCH,
    StickerRarity.RARE,
    ["clasico", "historia"],
  ),
  libertadoresSticker(
    11,
    "sl-011",
    "Defensor de otra epoca",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "defensor"],
  ),
  libertadoresSticker(
    12,
    "sl-012",
    "Mediocampista del ciclon",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "mediocampo"],
  ),
  libertadoresSticker(
    13,
    "sl-013",
    "La vuelta olimpica antigua",
    StickerCategory.HISTORIC_MOMENT,
    StickerRarity.COMMON,
    ["momento", "vuelta-olimpica"],
  ),
  libertadoresSticker(
    14,
    "sl-014",
    "Escudo de coleccion",
    StickerCategory.SPECIAL,
    StickerRarity.EPIC,
    ["especial", "escudo"],
  ),
  libertadoresSticker(
    15,
    "sl-015",
    "Campeon azulgrana de los 70",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.COMMON,
    ["campeonato", "historia"],
  ),
  libertadoresSticker(
    16,
    "sl-016",
    "Goleador moderno",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "goleador"],
  ),
  libertadoresSticker(
    17,
    "sl-017",
    "Arquero de penales",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "arquero"],
  ),
  libertadoresSticker(
    18,
    "sl-018",
    "Lateral incansable",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "defensor"],
  ),
  libertadoresSticker(
    19,
    "sl-019",
    "Volante de equilibrio",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "mediocampo"],
  ),
  libertadoresSticker(
    20,
    "sl-020",
    "Enganche azulgrana",
    StickerCategory.PLAYER,
    StickerRarity.UNCOMMON,
    ["jugador", "enganche"],
  ),
  libertadoresSticker(
    21,
    "sl-021",
    "Delantero de area",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "delantero"],
  ),
  libertadoresSticker(
    22,
    "sl-022",
    "Juvenil de cantera",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "cantera"],
  ),
  libertadoresSticker(
    23,
    "sl-023",
    "Capitan reciente",
    StickerCategory.PLAYER,
    StickerRarity.UNCOMMON,
    ["jugador", "capitan"],
  ),
  libertadoresSticker(
    24,
    "sl-024",
    "Tecnico campeon moderno",
    StickerCategory.COACH,
    StickerRarity.COMMON,
    ["tecnico", "campeon"],
  ),
  libertadoresSticker(
    25,
    "sl-025",
    "Tecnico de inferiores",
    StickerCategory.COACH,
    StickerRarity.COMMON,
    ["tecnico", "cantera"],
  ),
  libertadoresSticker(
    26,
    "sl-026",
    "Conductor tactico",
    StickerCategory.COACH,
    StickerRarity.UNCOMMON,
    ["tecnico", "tactica"],
  ),
  libertadoresSticker(
    27,
    "sl-027",
    "Titulo local moderno",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.COMMON,
    ["campeonato", "torneo-local"],
  ),
  libertadoresSticker(
    28,
    "sl-028",
    "Copa internacional",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.LEGENDARY,
    ["campeonato", "internacional"],
  ),
  libertadoresSticker(
    29,
    "sl-029",
    "Superfinal azulgrana",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.EPIC,
    ["campeonato", "final"],
  ),
  libertadoresSticker(
    30,
    "sl-030",
    "Gol en tiempo cumplido",
    StickerCategory.HISTORIC_MOMENT,
    StickerRarity.RARE,
    ["momento", "gol"],
  ),
  libertadoresSticker(
    31,
    "sl-031",
    "Noche de copa",
    StickerCategory.HISTORIC_MOMENT,
    StickerRarity.EPIC,
    ["momento", "copa"],
  ),
  libertadoresSticker(
    32,
    "sl-032",
    "Festejo en el Nuevo Gasometro",
    StickerCategory.HISTORIC_MOMENT,
    StickerRarity.UNCOMMON,
    ["momento", "festejo"],
  ),
  libertadoresSticker(
    33,
    "sl-033",
    "Nuevo Gasometro",
    StickerCategory.STADIUM,
    StickerRarity.RARE,
    ["estadio", "bajo-flores"],
  ),
  sticker(
    34,
    "sl-034",
    "Tribuna local",
    StickerCategory.STADIUM,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["estadio", "tribuna"],
  ),
  sticker(
    35,
    "sl-035",
    "Camiseta campeona",
    StickerCategory.JERSEY,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["camiseta", "campeona"],
  ),
  sticker(
    36,
    "sl-036",
    "Camiseta alternativa",
    StickerCategory.JERSEY,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["camiseta", "alternativa"],
  ),
  sticker(
    37,
    "sl-037",
    "Camiseta aniversario",
    StickerCategory.JERSEY,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["camiseta", "aniversario"],
  ),
  sticker(
    38,
    "sl-038",
    "Recibimiento azulgrana",
    StickerCategory.FANS,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["hinchada", "recibimiento"],
  ),
  sticker(
    39,
    "sl-039",
    "Caravana cuerva",
    StickerCategory.FANS,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["hinchada", "caravana"],
  ),
  sticker(
    40,
    "sl-040",
    "Clasico con remontada",
    StickerCategory.CLASSIC_MATCH,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["clasico", "remontada"],
  ),
  sticker(
    41,
    "sl-041",
    "Clasico de copa",
    StickerCategory.CLASSIC_MATCH,
    StickerEra.POST_1990,
    StickerRarity.EPIC,
    ["clasico", "copa"],
  ),
  sticker(
    42,
    "sl-042",
    "Clasico en casa",
    StickerCategory.CLASSIC_MATCH,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["clasico", "local"],
  ),
  sticker(
    43,
    "sl-043",
    "Cuervo especial",
    StickerCategory.SPECIAL,
    StickerEra.POST_1990,
    StickerRarity.LEGENDARY,
    ["especial", "simbolo"],
  ),
  sticker(
    44,
    "sl-044",
    "Sticker brillante azulgrana",
    StickerCategory.SPECIAL,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["especial", "brillante"],
  ),
  sticker(
    45,
    "sl-045",
    "Promesa ofensiva",
    StickerCategory.PLAYER,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["jugador", "cantera"],
  ),
  sticker(
    46,
    "sl-046",
    "Central de jerarquia",
    StickerCategory.PLAYER,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["jugador", "defensor"],
  ),
  sticker(
    47,
    "sl-047",
    "Mediapunta veloz",
    StickerCategory.PLAYER,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  sticker(
    48,
    "sl-048",
    "Extremo picante",
    StickerCategory.PLAYER,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  sticker(
    49,
    "sl-049",
    "Referente del vestuario",
    StickerCategory.PLAYER,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["jugador", "referente"],
  ),
  sticker(
    50,
    "sl-050",
    "Atajada inolvidable",
    StickerCategory.HISTORIC_MOMENT,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["momento", "arquero"],
  ),
];

function sticker(
  number: number,
  id: string,
  title: string,
  category: StickerCategory,
  era: StickerEra,
  rarity: StickerRarity,
  tags: readonly string[],
  options: { readonly description?: string; readonly tags?: readonly string[] } = {},
): Sticker {
  return {
    id,
    number,
    title,
    description:
      options.description ??
      `${title} - figurita placeholder para validar el flujo inicial del catalogo.`,
    category,
    era,
    rarity,
    imageUrl: getSeedImageUrl(number, id),
    tags: options.tags ?? tags,
    sortOrder: number,
    active: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  };
}

function libertadoresSticker(
  number: number,
  id: string,
  title: string,
  category: StickerCategory,
  rarity: StickerRarity,
  tags: readonly string[],
): Sticker {
  const era = number <= 15 ? StickerEra.PRE_1990 : StickerEra.POST_1990;

  return sticker(number, id, title, category, era, rarity, tags, {
    description: "",
    tags: [LIBERTADORES_2014_TAG, ...tags],
  });
}

function getSeedImageUrl(number: number, id: string): string {
  return LIBERTADORES_2014_IMAGE_URLS[number - 1] ?? `placeholder://albumsl/stickers/${id}`;
}
