import type { Sticker } from "../entities.js";
import { StickerCategory, StickerEra, StickerRarity } from "../enums.js";

export const INITIAL_STICKER_SEED_MIN_EXPECTED = 50;
const SEED_TIMESTAMP = new Date("2026-01-01T00:00:00.000Z");
const LIBERTADORES_2014_TAG = "libertadores-2014";
const LIBERTADORES_2014_IMAGE_URLS = [
  "/stickers/Libertadores_2014/libertadores_1.png",
  "/stickers/Libertadores_2014/libertadores_2.png",
  "/stickers/Libertadores_2014/libertadores_3.png",
  "/stickers/Libertadores_2014/Libertadores_4.jpg",
  "/stickers/Libertadores_2014/Libertadores_6.jpg",
  "/stickers/Libertadores_2014/libertadores_6.png",
  "/stickers/Libertadores_2014/libertadores_7.png",
  "/stickers/Libertadores_2014/libertadores_8.jpg",
  "/stickers/Libertadores_2014/libertadores_9.jpg",
  "/stickers/Libertadores_2014/libertadores_10.jpg",
  "/stickers/Libertadores_2014/libertadores_11.jpg",
  "/stickers/Libertadores_2014/libertadores_12.jpg",
  "/stickers/Libertadores_2014/libertadores_13.jpg",
  "/stickers/Libertadores_2014/libertadores_14.png",
  "/stickers/Libertadores_2014/libertadores_15.png",
  "/stickers/Libertadores_2014/libertadores_16.png",
  "/stickers/Libertadores_2014/libertadores_17.png",
  "/stickers/Libertadores_2014/libertadores_18.png",
  "/stickers/Libertadores_2014/libertadores_19.jpg",
  "/stickers/Libertadores_2014/libertadores_20.png",
  "/stickers/Libertadores_2014/libertadores_21.jpg",
  "/stickers/Libertadores_2014/libertadores_22.jpg",
  "/stickers/Libertadores_2014/libertadores_23.jpg",
  "/stickers/Libertadores_2014/libertadores_24.jpg",
  "/stickers/Libertadores_2014/libertadores_25.png",
  "/stickers/Libertadores_2014/libertadores_26.png",
  "/stickers/Libertadores_2014/libertadores_27.png",
  "/stickers/Libertadores_2014/libertadores_28.png",
  "/stickers/Libertadores_2014/libertadores_29.jpg",
  "/stickers/Libertadores_2014/libertadores_30.png",
  "/stickers/Libertadores_2014/libertadores_31.png",
  "/stickers/Libertadores_2014/libertadores_32.png",
  "/stickers/Libertadores_2014/libertadores_33.png",
] as const;

export const initialStickerSeed: readonly Sticker[] = [
  libertadoresSticker(
    1,
    "sl-001",
    "Copa levantada",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.LEGENDARY,
    ["copa", "campeon", "festejo"],
  ),
  libertadoresSticker(
    2,
    "sl-002",
    "Salida campeona",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.EPIC,
    ["copa", "plantel", "festejo"],
  ),
  libertadoresSticker(
    3,
    "sl-003",
    "Avance azulgrana",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  libertadoresSticker(4, "sl-004", "Padre de la Copa", StickerCategory.COACH, StickerRarity.EPIC, [
    "tecnico",
    "copa",
  ]),
  libertadoresSticker(
    5,
    "sl-005",
    "Frase de campeon",
    StickerCategory.COACH,
    StickerRarity.COMMON,
    ["tecnico", "campeon"],
  ),
  libertadoresSticker(
    6,
    "sl-006",
    "Noche en el Nuevo Gasometro",
    StickerCategory.STADIUM,
    StickerRarity.RARE,
    ["estadio", "copa"],
  ),
  libertadoresSticker(
    7,
    "sl-007",
    "Arco de Copa",
    StickerCategory.CLASSIC_MATCH,
    StickerRarity.UNCOMMON,
    ["partido", "area"],
  ),
  libertadoresSticker(
    8,
    "sl-008",
    "Abrazo de semifinal",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "festejo"],
  ),
  libertadoresSticker(
    9,
    "sl-009",
    "Grito azulgrana",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "festejo"],
  ),
  libertadoresSticker(
    10,
    "sl-010",
    "Banco azulgrana",
    StickerCategory.COACH,
    StickerRarity.COMMON,
    ["tecnico", "partido"],
  ),
  libertadoresSticker(
    11,
    "sl-011",
    "Duelo por la punta",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  libertadoresSticker(
    12,
    "sl-012",
    "Ataque por derecha",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  libertadoresSticker(
    13,
    "sl-013",
    "La Copa en el cesped",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.EPIC,
    ["copa", "trofeo"],
  ),
  libertadoresSticker(
    14,
    "sl-014",
    "Desborde por izquierda",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  libertadoresSticker(
    15,
    "sl-015",
    "Grito bajo la lluvia",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "festejo"],
  ),
  libertadoresSticker(
    16,
    "sl-016",
    "Recibimiento copero",
    StickerCategory.FANS,
    StickerRarity.RARE,
    ["hinchada", "copa"],
  ),
  libertadoresSticker(
    17,
    "sl-017",
    "Copa en alto",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.LEGENDARY,
    ["copa", "trofeo"],
  ),
  libertadoresSticker(18, "sl-018", "Fuegos de final", StickerCategory.FANS, StickerRarity.EPIC, [
    "hinchada",
    "festejo",
  ]),
  libertadoresSticker(
    19,
    "sl-019",
    "Festejo de goleador",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "gol"],
  ),
  libertadoresSticker(
    20,
    "sl-020",
    "Pase a la historia",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "pase"],
  ),
  libertadoresSticker(
    21,
    "sl-021",
    "Plantel campeon",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.RARE,
    ["plantel", "campeon"],
  ),
  libertadoresSticker(
    22,
    "sl-022",
    "Campeones con la Copa",
    StickerCategory.CHAMPIONSHIP,
    StickerRarity.UNCOMMON,
    ["copa", "plantel"],
  ),
  libertadoresSticker(
    23,
    "sl-023",
    "Abrazo de campeones",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "festejo"],
  ),
  libertadoresSticker(
    24,
    "sl-024",
    "Pelota en el area",
    StickerCategory.CLASSIC_MATCH,
    StickerRarity.COMMON,
    ["partido", "area"],
  ),
  libertadoresSticker(
    25,
    "sl-025",
    "Celebracion de punta",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["jugador", "festejo"],
  ),
  libertadoresSticker(26, "sl-026", "Gol y abrazo", StickerCategory.PLAYER, StickerRarity.COMMON, [
    "jugador",
    "gol",
  ]),
  libertadoresSticker(
    27,
    "sl-027",
    "Beso al escudo",
    StickerCategory.PLAYER,
    StickerRarity.UNCOMMON,
    ["jugador", "escudo"],
  ),
  libertadoresSticker(28, "sl-028", "Atajada clave", StickerCategory.PLAYER, StickerRarity.RARE, [
    "jugador",
    "arquero",
  ]),
  libertadoresSticker(
    29,
    "sl-029",
    "Arquero de la final",
    StickerCategory.PLAYER,
    StickerRarity.RARE,
    ["jugador", "arquero"],
  ),
  libertadoresSticker(
    30,
    "sl-030",
    "Cruce de Copa",
    StickerCategory.CLASSIC_MATCH,
    StickerRarity.COMMON,
    ["partido", "copa"],
  ),
  libertadoresSticker(
    31,
    "sl-031",
    "Equipo titular",
    StickerCategory.PLAYER,
    StickerRarity.COMMON,
    ["plantel", "partido"],
  ),
  libertadoresSticker(32, "sl-032", "Gol celebrado", StickerCategory.PLAYER, StickerRarity.COMMON, [
    "jugador",
    "gol",
  ]),
  libertadoresSticker(
    33,
    "sl-033",
    "Brazos al cielo",
    StickerCategory.PLAYER,
    StickerRarity.UNCOMMON,
    ["jugador", "festejo"],
  ),
  sticker(
    34,
    "sl-034",
    "Tablon de Boedo",
    StickerCategory.STADIUM,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["estadio", "boedo"],
  ),
  sticker(
    35,
    "sl-035",
    "Bastones fundacionales",
    StickerCategory.JERSEY,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["camiseta", "historia"],
  ),
  sticker(
    36,
    "sl-036",
    "Camiseta azulgrana clasica",
    StickerCategory.JERSEY,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["camiseta", "clasica"],
  ),
  sticker(
    37,
    "sl-037",
    "Casaca de epoca",
    StickerCategory.JERSEY,
    StickerEra.PRE_1990,
    StickerRarity.UNCOMMON,
    ["camiseta", "historia"],
  ),
  sticker(
    38,
    "sl-038",
    "Aliento de tablon",
    StickerCategory.FANS,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["hinchada", "boedo"],
  ),
  sticker(
    39,
    "sl-039",
    "Caravana a Boedo",
    StickerCategory.FANS,
    StickerEra.PRE_1990,
    StickerRarity.UNCOMMON,
    ["hinchada", "boedo"],
  ),
  sticker(
    40,
    "sl-040",
    "Clasico de barrio",
    StickerCategory.CLASSIC_MATCH,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["clasico", "barrio"],
  ),
  sticker(
    41,
    "sl-041",
    "Clasico historico",
    StickerCategory.CLASSIC_MATCH,
    StickerEra.PRE_1990,
    StickerRarity.RARE,
    ["clasico", "historia"],
  ),
  sticker(
    42,
    "sl-042",
    "Tarde de clasico",
    StickerCategory.CLASSIC_MATCH,
    StickerEra.PRE_1990,
    StickerRarity.UNCOMMON,
    ["clasico", "partido"],
  ),
  sticker(
    43,
    "sl-043",
    "Cuervo historico",
    StickerCategory.SPECIAL,
    StickerEra.PRE_1990,
    StickerRarity.RARE,
    ["especial", "historia"],
  ),
  sticker(
    44,
    "sl-044",
    "Brillante de coleccion",
    StickerCategory.SPECIAL,
    StickerEra.PRE_1990,
    StickerRarity.UNCOMMON,
    ["especial", "coleccion"],
  ),
  sticker(
    45,
    "sl-045",
    "Promesa de inferiores",
    StickerCategory.PLAYER,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["jugador", "inferiores"],
  ),
  sticker(
    46,
    "sl-046",
    "Central de otra epoca",
    StickerCategory.PLAYER,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["jugador", "defensor"],
  ),
  sticker(
    47,
    "sl-047",
    "Mediapunta de potrero",
    StickerCategory.PLAYER,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["jugador", "potrero"],
  ),
  sticker(
    48,
    "sl-048",
    "Extremo de los tablones",
    StickerCategory.PLAYER,
    StickerEra.PRE_1990,
    StickerRarity.COMMON,
    ["jugador", "ataque"],
  ),
  sticker(
    49,
    "sl-049",
    "Referente azulgrana actual",
    StickerCategory.PLAYER,
    StickerEra.POST_1990,
    StickerRarity.UNCOMMON,
    ["jugador", "referente"],
  ),
  sticker(
    50,
    "sl-050",
    "Atajada moderna",
    StickerCategory.HISTORIC_MOMENT,
    StickerEra.POST_1990,
    StickerRarity.COMMON,
    ["momento", "arquero"],
  ),
];

function sticker(
  number: number,
  id: string,
  title: string,
  category: StickerCategory,
  era: StickerEra,
  rarity: StickerRarity,
  tags: readonly string[],
  options: { readonly description?: string; readonly tags?: readonly string[] } = {},
): Sticker {
  return {
    id,
    number,
    title,
    description:
      options.description ??
      `${title} - figurita placeholder para validar el flujo inicial del catalogo.`,
    category,
    era,
    rarity,
    imageUrl: getSeedImageUrl(number, id),
    tags: options.tags ?? tags,
    sortOrder: number,
    active: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  };
}

function libertadoresSticker(
  number: number,
  id: string,
  title: string,
  category: StickerCategory,
  rarity: StickerRarity,
  tags: readonly string[],
): Sticker {
  return sticker(number, id, title, category, StickerEra.POST_1990, rarity, tags, {
    description: "",
    tags: [LIBERTADORES_2014_TAG, ...tags],
  });
}

function getSeedImageUrl(number: number, id: string): string {
  return LIBERTADORES_2014_IMAGE_URLS[number - 1] ?? `placeholder://albumsl/stickers/${id}`;
}
